"""Delta-hedged option-native probes for the R4 VELVET voucher complex.

This harness intentionally isolates option families from the static R3
schedule:

* long-gamma probes: buy core vouchers when trailing realized vol exceeds IV;
* rich-wing probes: sell high smile-residual wings in small size;
* both families delta hedge with VELVET at the sampled book touch.

It is a mechanism test. It uses sampled IV/Greek rows generated by
``analyze_velvet_option_complex`` and should not be treated as exact live fill
simulation.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_FEATURES = REPO_ROOT / "outputs" / "round_4" / "velvet_option_complex" / "option_iv_greeks_smile.csv"
DEFAULT_OUT_DIR = REPO_ROOT / "outputs" / "round_4" / "gamma_smile_probes"
DEFAULT_DOC = REPO_ROOT / "docs" / "round_4" / "GAMMA_SMILE_PROBES.md"

UNDERLYING = "VELVETFRUIT_EXTRACT"
OPTION_LIMIT = 300
UNDERLYING_LIMIT = 200


@dataclass(frozen=True)
class ProbeConfig:
    label: str
    family: str
    products: tuple[str, ...]
    max_pos: int
    max_order: int
    delta_band: float
    vol_edge: float = 0.0
    residual_edge: float = 0.0
    max_spread: float = 10.0
    flatten_after: int | None = None


@dataclass
class Portfolio:
    products: tuple[str, ...]
    cash: dict[str, float]
    position: dict[str, int]
    trades: list[dict]
    peak: float = -float("inf")
    max_drawdown: float = 0.0

    @classmethod
    def create(cls, products: tuple[str, ...]) -> "Portfolio":
        all_products = (UNDERLYING, *products)
        return cls(
            products=products,
            cash={product: 0.0 for product in all_products},
            position={product: 0 for product in all_products},
            trades=[],
        )

    def buy(self, dataset: str, day: int, timestamp: int, product: str, price: float, qty: int, reason: str) -> int:
        qty = int(max(0, qty))
        if qty <= 0:
            return 0
        qty = min(qty, (UNDERLYING_LIMIT if product == UNDERLYING else OPTION_LIMIT) - self.position.get(product, 0))
        if qty <= 0:
            return 0
        self.cash[product] -= float(price) * qty
        self.position[product] = self.position.get(product, 0) + qty
        self.trades.append(_trade_row(dataset, day, timestamp, product, "buy", price, qty, reason, self.position[product]))
        return qty

    def sell(self, dataset: str, day: int, timestamp: int, product: str, price: float, qty: int, reason: str) -> int:
        qty = int(max(0, qty))
        if qty <= 0:
            return 0
        qty = min(qty, (UNDERLYING_LIMIT if product == UNDERLYING else OPTION_LIMIT) + self.position.get(product, 0))
        if qty <= 0:
            return 0
        self.cash[product] += float(price) * qty
        self.position[product] = self.position.get(product, 0) - qty
        self.trades.append(_trade_row(dataset, day, timestamp, product, "sell", price, qty, reason, self.position[product]))
        return qty

    def mark(self, mids: dict[str, float]) -> float:
        total = 0.0
        for product, cash in self.cash.items():
            total += cash + self.position.get(product, 0) * mids.get(product, 0.0)
        return total

    def observe(self, pnl: float) -> float:
        self.peak = max(self.peak, pnl)
        self.max_drawdown = min(self.max_drawdown, pnl - self.peak)
        return self.max_drawdown


def _trade_row(dataset: str, day: int, timestamp: int, product: str, side: str, price: float, qty: int, reason: str, pos_after: int) -> dict:
    return {
        "dataset": dataset,
        "day": int(day),
        "timestamp": int(timestamp),
        "product": product,
        "side": side,
        "price": float(price),
        "qty": int(qty),
        "reason": reason,
        "pos_after": int(pos_after),
    }


def load_features(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    # Use regular sampled snapshots for strategy evaluation, not extra fill
    # timestamps inherited from the schedule attribution pass.
    df = df[df["timestamp"].mod(1_000).eq(0)].copy()
    for column in ["iv", "rv_back_30000", "iv_residual", "price_residual", "delta"]:
        df[column] = pd.to_numeric(df[column], errors="coerce")
    return df.sort_values(["dataset", "day", "timestamp", "product"]).reset_index(drop=True)


def _configs() -> list[ProbeConfig]:
    return [
        ProbeConfig(
            "long_gamma_5100_5200_edge002_pos60_q10_d50",
            "long_gamma",
            ("VEV_5100", "VEV_5200"),
            max_pos=60,
            max_order=10,
            delta_band=50,
            vol_edge=0.002,
            residual_edge=0.001,
            max_spread=6,
        ),
        ProbeConfig(
            "long_gamma_5100_5200_edge004_pos60_q10_d50",
            "long_gamma",
            ("VEV_5100", "VEV_5200"),
            max_pos=60,
            max_order=10,
            delta_band=50,
            vol_edge=0.004,
            residual_edge=0.001,
            max_spread=6,
        ),
        ProbeConfig(
            "long_gamma_5000_5100_5200_edge003_pos40_q8_d50",
            "long_gamma",
            ("VEV_5000", "VEV_5100", "VEV_5200"),
            max_pos=40,
            max_order=8,
            delta_band=50,
            vol_edge=0.003,
            residual_edge=0.001,
            max_spread=7,
        ),
        ProbeConfig(
            "rich_wing_5300_5500_resid001_price1_pos60_q10_d50",
            "rich_wing_short",
            ("VEV_5300", "VEV_5500"),
            max_pos=60,
            max_order=10,
            delta_band=50,
            residual_edge=0.001,
            max_spread=4,
        ),
        ProbeConfig(
            "rich_wing_5300_5500_resid002_price2_pos40_q8_d50",
            "rich_wing_short",
            ("VEV_5300", "VEV_5500"),
            max_pos=40,
            max_order=8,
            delta_band=50,
            residual_edge=0.002,
            max_spread=4,
        ),
    ]


def _should_long(row: pd.Series, cfg: ProbeConfig) -> bool:
    if pd.isna(row["iv"]) or pd.isna(row["rv_back_30000"]):
        return False
    if float(row["spread"]) > cfg.max_spread:
        return False
    if float(row["iv"]) > float(row["rv_back_30000"]) - cfg.vol_edge:
        return False
    if pd.notna(row["iv_residual"]) and float(row["iv_residual"]) > cfg.residual_edge:
        return False
    return True


def _should_short_rich(row: pd.Series, cfg: ProbeConfig) -> bool:
    if pd.isna(row["iv_residual"]) or pd.isna(row["price_residual"]):
        return False
    if float(row["spread"]) > cfg.max_spread:
        return False
    return float(row["iv_residual"]) >= cfg.residual_edge and float(row["price_residual"]) >= max(1.0, cfg.residual_edge * 1000)


def _net_delta(portfolio: Portfolio, rows: pd.DataFrame) -> float:
    delta = float(portfolio.position.get(UNDERLYING, 0))
    for row in rows.itertuples(index=False):
        delta += portfolio.position.get(str(row.product), 0) * float(row.delta if pd.notna(row.delta) else 0.0)
    return delta


def _hedge(portfolio: Portfolio, dataset: str, day: int, timestamp: int, rows: pd.DataFrame, cfg: ProbeConfig) -> None:
    delta = _net_delta(portfolio, rows)
    first = rows.iloc[0]
    if abs(delta) <= cfg.delta_band:
        return
    if delta > cfg.delta_band and pd.notna(first["spot_bid"]):
        qty = int(np.ceil(delta - cfg.delta_band))
        portfolio.sell(dataset, day, timestamp, UNDERLYING, float(first["spot_bid"]), min(cfg.max_order * 2, qty), "delta_hedge")
    elif delta < -cfg.delta_band and pd.notna(first["spot_ask"]):
        qty = int(np.ceil(-delta - cfg.delta_band))
        portfolio.buy(dataset, day, timestamp, UNDERLYING, float(first["spot_ask"]), min(cfg.max_order * 2, qty), "delta_hedge")


def simulate_path(features: pd.DataFrame, cfg: ProbeConfig) -> tuple[pd.DataFrame, pd.DataFrame]:
    trades = []
    pnl_rows = []
    for (dataset, day), day_df in features.groupby(["dataset", "day"], sort=False):
        portfolio = Portfolio.create(cfg.products)
        for timestamp, rows in day_df.groupby("timestamp", sort=True):
            timestamp = int(timestamp)
            rows = rows[rows["product"].isin(cfg.products)].copy()
            if rows.empty:
                continue
            mids = {UNDERLYING: float(rows.iloc[0]["spot_mid"])}
            mids.update({str(row.product): float(row.mid) for row in rows.itertuples(index=False)})

            for _, row in rows.iterrows():
                product = str(row["product"])
                pos = portfolio.position.get(product, 0)
                if cfg.family == "long_gamma":
                    active = _should_long(row, cfg)
                    if active and pos < cfg.max_pos and pd.notna(row["ask"]):
                        qty = min(cfg.max_order, cfg.max_pos - pos)
                        portfolio.buy(str(dataset), int(day), timestamp, product, float(row["ask"]), qty, "long_gamma_entry")
                    elif (not active or (cfg.flatten_after is not None and timestamp >= cfg.flatten_after)) and pos > 0 and pd.notna(row["bid"]):
                        portfolio.sell(str(dataset), int(day), timestamp, product, float(row["bid"]), min(cfg.max_order, pos), "long_gamma_exit")
                elif cfg.family == "rich_wing_short":
                    active = _should_short_rich(row, cfg)
                    if active and pos > -cfg.max_pos and pd.notna(row["bid"]):
                        qty = min(cfg.max_order, cfg.max_pos + pos)
                        portfolio.sell(str(dataset), int(day), timestamp, product, float(row["bid"]), qty, "rich_wing_entry")
                    elif (not active or (cfg.flatten_after is not None and timestamp >= cfg.flatten_after)) and pos < 0 and pd.notna(row["ask"]):
                        portfolio.buy(str(dataset), int(day), timestamp, product, float(row["ask"]), min(cfg.max_order, -pos), "rich_wing_exit")

            _hedge(portfolio, str(dataset), int(day), timestamp, rows, cfg)
            pnl = portfolio.mark(mids)
            dd = portfolio.observe(pnl)
            pnl_rows.append(
                {
                    "variant": cfg.label,
                    "dataset": dataset,
                    "day": int(day),
                    "timestamp": timestamp,
                    "total_pnl": pnl,
                    "drawdown": dd,
                    "net_delta": _net_delta(portfolio, rows),
                    **{f"pos_{product}": portfolio.position.get(product, 0) for product in (UNDERLYING, *cfg.products)},
                }
            )
        trades.extend({**row, "variant": cfg.label} for row in portfolio.trades)
    return pd.DataFrame(trades), pd.DataFrame(pnl_rows)


def summarize(trades: pd.DataFrame, pnl: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for (variant, dataset, day), group in pnl.groupby(["variant", "dataset", "day"], sort=False):
        last = group.sort_values("timestamp").iloc[-1]
        t = trades[(trades["variant"] == variant) & (trades["dataset"] == dataset) & (trades["day"] == day)]
        rows.append(
            {
                "variant": variant,
                "dataset": dataset,
                "day": int(day),
                "total_pnl": float(last["total_pnl"]),
                "max_drawdown": float(group["drawdown"].min()),
                "max_abs_delta": float(group["net_delta"].abs().max()),
                "trades": int(len(t)),
                "abs_qty": int(t["qty"].sum()) if not t.empty else 0,
                "end_net_delta": float(last["net_delta"]),
            }
        )
    return pd.DataFrame(rows)


def markdown_table(df: pd.DataFrame, *, max_rows: int = 60) -> str:
    if df.empty:
        return "_empty_"
    display = df.head(max_rows).copy()
    for column in display.columns:
        if pd.api.types.is_float_dtype(display[column]):
            display[column] = display[column].map(lambda v: f"{v:.2f}")
    headers = [str(c) for c in display.columns]
    rows = [[str(v) for v in row] for row in display.to_numpy()]
    widths = [len(h) for h in headers]
    for row in rows:
        for i, cell in enumerate(row):
            widths[i] = max(widths[i], len(cell))

    def fmt(values: list[str]) -> str:
        return "| " + " | ".join(values[i].ljust(widths[i]) for i in range(len(widths))) + " |"

    return "\n".join([fmt(headers), "| " + " | ".join("-" * w for w in widths) + " |", *(fmt(r) for r in rows)])


def write_report(doc: Path, out_dir: Path, summary: pd.DataFrame) -> None:
    historical = summary[summary["dataset"] == "historical"]
    official = summary[summary["dataset"].str.contains("official", na=False)]
    agg = (
        historical.groupby("variant", sort=False)
        .agg(
            mean_total=("total_pnl", "mean"),
            min_total=("total_pnl", "min"),
            mean_drawdown=("max_drawdown", "mean"),
            max_abs_delta=("max_abs_delta", "max"),
            mean_trades=("trades", "mean"),
        )
        .reset_index()
        .sort_values("mean_total", ascending=False)
    )
    text = f"""# Gamma / Smile Probe Results

Generated by:

```bash
PYTHONPATH=. .venv/bin/python -m src.scripts.round_4.test_gamma_smile_probes
```

Artifacts live under `{out_dir}`.

## Historical Summary

{markdown_table(agg)}

## Official 100k Proxy

{markdown_table(official.sort_values(["dataset", "total_pnl"], ascending=[True, False]), max_rows=80)}

## Read

These are isolated option-native probes, not combined candidates. Promote only
if a family is positive across historical days and does not rely on excessive
residual delta. A weak result here does not disprove gamma alpha; it only says
this minimal implementation is not enough.
"""
    doc.write_text(text)


def run(features_path: Path, out_dir: Path, doc: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    doc.parent.mkdir(parents=True, exist_ok=True)
    features = load_features(features_path)
    all_trades = []
    all_pnl = []
    for cfg in _configs():
        print(f"running {cfg.label}", flush=True)
        trades, pnl = simulate_path(features, cfg)
        all_trades.append(trades)
        all_pnl.append(pnl)
    trades = pd.concat(all_trades, ignore_index=True)
    pnl = pd.concat(all_pnl, ignore_index=True)
    summary = summarize(trades, pnl)
    trades.to_csv(out_dir / "gamma_smile_trades.csv", index=False)
    pnl.to_csv(out_dir / "gamma_smile_pnl_path.csv", index=False)
    summary.to_csv(out_dir / "gamma_smile_summary.csv", index=False)
    write_report(doc, out_dir, summary)
    print(f"Wrote {out_dir}")
    print(f"Wrote {doc}")
    print(summary.sort_values(["dataset", "day", "total_pnl"], ascending=[True, True, False]).to_string(index=False))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--features", type=Path, default=DEFAULT_FEATURES)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--doc", type=Path, default=DEFAULT_DOC)
    args = parser.parse_args()
    run(args.features, args.out_dir, args.doc)


if __name__ == "__main__":
    main()
