"""Evaluate VELVETFRUIT_EXTRACT recycle probes on top of `sell7`.

The largest remaining official L1 oracle gap after `sell7` is the underlying.
Current schedule sells the early high but usually remains pinned short because
its buy threshold is just below the later official low ask. This harness tests
state-light threshold schedules that keep the early short but allow a later
cover/re-short cycle.
"""

from __future__ import annotations

import argparse
from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from src.scripts.round_4.analyze_velvet_option_complex import (
    DEFAULT_DATA_DIR,
    DEFAULT_OFFICIAL_DIR,
    SELL7_SCHEDULES,
    UNDERLYING,
    load_historical,
    load_official_books,
    simulate_schedule,
    summarize_pnl,
)
from src.scripts.round_4.test_core_recycler_probes import markdown_table


REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_OUT_DIR = REPO_ROOT / "outputs" / "round_4" / "velvet_recycle"
DEFAULT_DOC = REPO_ROOT / "docs" / "round_4" / "VELVET_RECYCLE_PROBES.md"


@dataclass(frozen=True)
class VelvetProbe:
    label: str
    schedule: tuple[tuple[int, dict[str, int]], ...]


def _schedules_with_velvet(schedule: tuple[tuple[int, dict[str, int]], ...]) -> dict:
    schedules = deepcopy(SELL7_SCHEDULES)
    schedules[UNDERLYING] = tuple((ts, dict(cfg)) for ts, cfg in schedule)
    return schedules


def _configs() -> list[VelvetProbe]:
    base_cfg = {"limit": 200, "max_order": 40, "buy": 5246, "sell": 5272}
    return [
        VelvetProbe("sell7_base", ((0, base_cfg),)),
        VelvetProbe(
            "velvet_after30k_buy5247_sell5264",
            (
                (0, base_cfg),
                (30_000, {"limit": 200, "max_order": 40, "buy": 5247, "sell": 5264}),
            ),
        ),
        VelvetProbe(
            "velvet_after30k_buy5248_sell5264",
            (
                (0, base_cfg),
                (30_000, {"limit": 200, "max_order": 40, "buy": 5248, "sell": 5264}),
            ),
        ),
        VelvetProbe(
            "velvet_after30k_buy5247_sell5262",
            (
                (0, base_cfg),
                (30_000, {"limit": 200, "max_order": 40, "buy": 5247, "sell": 5262}),
            ),
        ),
        VelvetProbe(
            "velvet_after50k_buy5247_sell5264",
            (
                (0, base_cfg),
                (50_000, {"limit": 200, "max_order": 40, "buy": 5247, "sell": 5264}),
            ),
        ),
        VelvetProbe(
            "negctrl_after30k_buy5247_sell5272",
            (
                (0, base_cfg),
                (30_000, {"limit": 200, "max_order": 40, "buy": 5247, "sell": 5272}),
            ),
        ),
    ]


def write_report(doc: Path, out_dir: Path, summary: pd.DataFrame, trades: pd.DataFrame) -> None:
    hist = summary[summary["dataset"] == "historical"].copy()
    official = summary[summary["dataset"].str.contains("official", na=False)].copy()
    agg = (
        hist.groupby("variant", sort=False)
        .agg(
            mean_total=("total_pnl", "mean"),
            min_total=("total_pnl", "min"),
            mean_drawdown=("max_drawdown", "mean"),
            mean_velvet=("VELVETFRUIT_EXTRACT_pnl", "mean"),
        )
        .reset_index()
    )
    base_total = float(agg.loc[agg["variant"] == "sell7_base", "mean_total"].iloc[0])
    agg["delta_vs_base"] = agg["mean_total"] - base_total
    official_view = official[
        [
            "variant",
            "dataset",
            "total_pnl",
            "max_drawdown",
            "first_ts_99pct",
            "VELVETFRUIT_EXTRACT_pnl",
            "VEV_5500_pnl",
        ]
    ]
    velvet_trades = trades[trades["product"] == UNDERLYING]
    trade_view = (
        velvet_trades.groupby(["variant", "dataset", "day", "side"], sort=False)
        .agg(qty=("qty", "sum"), avg_price=("price", "mean"), first_ts=("timestamp", "min"), last_ts=("timestamp", "max"))
        .reset_index()
    )
    text = f"""# VELVET Recycle Probe Results

Generated by:

```bash
PYTHONPATH=. .venv/bin/python -m src.scripts.round_4.test_velvet_recycle_probes
```

Artifacts live under `{out_dir}`.

## Mechanism

These probes keep the early `sell7` voucher schedule intact and only alter the
underlying after the first 30k/50k ticks. The intended capture is: sell the
early VELVET high, cover when the later low ask is available, and optionally
re-short a rebound.

## Historical Three-Day Summary

{markdown_table(agg.sort_values("delta_vs_base", ascending=False), max_rows=80)}

## Official 100k Book Proxy

{markdown_table(official_view.sort_values(["dataset", "total_pnl"], ascending=[True, False]), max_rows=100)}

## VELVET Trade Summary

{markdown_table(trade_view, max_rows=120)}

## Read

Promote only if the schedule improves historical mean and does not merely key
off the official one-tick miss. The negative control raises only the cover
threshold; if it captures most of the benefit, the re-short threshold is less
important than avoiding an over-pinned short.
"""
    doc.write_text(text)


def run(data_dir: Path, official_dir: Path, out_dir: Path, doc: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    doc.parent.mkdir(parents=True, exist_ok=True)
    historical = load_historical(data_dir)
    official_books, _ = load_official_books(official_dir)
    official = [
        book
        for name, book in official_books.items()
        if name in {"official_sellonly8", "official_disabled", "official_sell7_validated"}
    ]
    prices = pd.concat([historical, *official], ignore_index=True)
    runs = []
    for cfg in _configs():
        print(f"running {cfg.label}", flush=True)
        runs.append(simulate_schedule(prices, schedules=_schedules_with_velvet(cfg.schedule), label=cfg.label))
    summary = pd.concat([summarize_pnl(run) for run in runs], ignore_index=True)
    trades = pd.concat([run.trades for run in runs], ignore_index=True)
    paths = pd.concat([run.path for run in runs], ignore_index=True)
    summary.to_csv(out_dir / "velvet_recycle_summary.csv", index=False)
    trades.to_csv(out_dir / "velvet_recycle_trades.csv", index=False)
    paths.to_csv(out_dir / "velvet_recycle_pnl_path.csv", index=False)
    write_report(doc, out_dir, summary, trades)
    print(f"Wrote {out_dir}")
    print(f"Wrote {doc}")
    print(summary.sort_values(["dataset", "day", "total_pnl"], ascending=[True, True, False]).to_string(index=False))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR)
    parser.add_argument("--official-dir", type=Path, default=DEFAULT_OFFICIAL_DIR)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--doc", type=Path, default=DEFAULT_DOC)
    args = parser.parse_args()
    run(args.data_dir, args.official_dir, args.out_dir, args.doc)


if __name__ == "__main__":
    main()
