# Auto-generated by src/scripts/export_submission.py. DO NOT EDIT.
# Datamodel mode: platform.
# Source modules: 7.

from __future__ import annotations

from datamodel import Order, OrderDepth, Trade, TradingState

from collections.abc import Mapping
from dataclasses import dataclass, field
from types import MappingProxyType
from typing import Literal
import math
from dataclasses import dataclass
import json
from collections import defaultdict

# ========================================================================
# src/core/types.py
# ========================================================================

"""Shared engine types.

These types are the stable vocabulary spoken by every engine layer:
fair value, signals, execution, risk, and strategies.

Design notes:
- ``NormalizedSnapshot`` is frozen. Downstream code should not mutate it.
- ``ProductMemory`` is mutable because it is the authoritative rolling state
  we persist through ``traderData``; mutation is explicit and local.
- ``FairValueEstimate`` and ``SignalIntent`` are frozen so strategy code
  cannot accidentally mutate outputs of the fair value or signal stages.
  Their container fields (``components``, ``metadata``) are typed as
  ``Mapping`` and default to ``MappingProxyType({})`` so mutation is
  rejected at runtime as well as discouraged by the type system.
"""



Product = str
Timestamp = int
Scalar = int | float | str | bool
ExecutionMode = Literal["idle", "maker", "taker", "recovery", "hybrid"]


def _empty_scalar_map() -> Mapping[str, Scalar]:
    return MappingProxyType({})


@dataclass(frozen=True)
class BookLevel:
    price: int
    volume: int


@dataclass(frozen=True)
class TradePrint:
    price: int
    quantity: int
    buyer: str | None = None
    seller: str | None = None
    timestamp: int = 0
    source: Literal["own", "market"] = "market"


@dataclass(frozen=True)
class NormalizedSnapshot:
    product: Product
    timestamp: Timestamp
    bids: tuple[BookLevel, ...] = ()
    asks: tuple[BookLevel, ...] = ()
    position: int = 0
    trades: tuple[TradePrint, ...] = ()

    @property
    def best_bid(self) -> BookLevel | None:
        return self.bids[0] if self.bids else None

    @property
    def best_ask(self) -> BookLevel | None:
        return self.asks[0] if self.asks else None

    @property
    def mid(self) -> float | None:
        if self.best_bid is None or self.best_ask is None:
            return None
        return (self.best_bid.price + self.best_ask.price) / 2.0

    @property
    def spread(self) -> float | None:
        if self.best_bid is None or self.best_ask is None:
            return None
        return float(self.best_ask.price - self.best_bid.price)

    @property
    def book_imbalance(self) -> float | None:
        """Top-of-book imbalance in [-1, 1], positive = bid-heavy."""
        if self.best_bid is None or self.best_ask is None:
            return None
        total = self.best_bid.volume + self.best_ask.volume
        if total <= 0:
            return None
        return (self.best_bid.volume - self.best_ask.volume) / total

    @property
    def microprice(self) -> float | None:
        """Volume-weighted best price, i.e. mid tilted toward the thicker side."""
        if self.best_bid is None or self.best_ask is None:
            return None
        total = self.best_bid.volume + self.best_ask.volume
        if total <= 0:
            return None
        return (
            (self.best_bid.price * self.best_ask.volume)
            + (self.best_ask.price * self.best_bid.volume)
        ) / total

    def total_bid_volume(self, depth: int | None = None) -> int:
        levels = self.bids if depth is None else self.bids[:depth]
        return sum(level.volume for level in levels)

    def total_ask_volume(self, depth: int | None = None) -> int:
        levels = self.asks if depth is None else self.asks[:depth]
        return sum(level.volume for level in levels)

    def top_bids(self, depth: int) -> tuple[BookLevel, ...]:
        if depth <= 0:
            return ()
        return self.bids[:depth]

    def top_asks(self, depth: int) -> tuple[BookLevel, ...]:
        if depth <= 0:
            return ()
        return self.asks[:depth]


@dataclass
class ProductMemory:
    recent_mids: list[float] = field(default_factory=list)
    recent_spreads: list[float] = field(default_factory=list)
    counters: dict[str, int] = field(default_factory=dict)
    flags: dict[str, bool] = field(default_factory=dict)
    values: dict[str, float] = field(default_factory=dict)


@dataclass
class EngineState:
    """Persistent state carried across ticks via ``traderData``.

    - ``products``: legacy per-product rolling memory (unchanged).
    - ``engines``: R3+ cross-product engine state keyed by engine_id.
      Each engine owns its own JSON-serializable sub-dict. StateStore
      round-trips the dict; engines are responsible for their own
      serialization shape via ``to_state()`` / ``from_state()``.
    """

    version: int = 1
    products: dict[Product, ProductMemory] = field(default_factory=dict)
    engines: dict[str, dict] = field(default_factory=dict)

    def for_product(self, product: Product) -> ProductMemory:
        memory = self.products.get(product)
        if memory is None:
            memory = ProductMemory()
            self.products[product] = memory
        return memory

    def for_engine(self, engine_id: str) -> dict:
        """Return the persisted state blob for an engine, or an empty dict."""
        blob = self.engines.get(engine_id)
        if blob is None:
            blob = {}
            self.engines[engine_id] = blob
        return blob

    def set_engine_state(self, engine_id: str, blob: dict) -> None:
        """Overwrite the persisted state for an engine."""
        self.engines[engine_id] = blob


@dataclass(frozen=True)
class FairValueEstimate:
    price: float
    method: str
    confidence: float | None = None
    components: Mapping[str, Scalar] = field(default_factory=_empty_scalar_map)


@dataclass(frozen=True)
class QuoteIntent:
    bid_price: int | None = None
    bid_size: int = 0
    ask_price: int | None = None
    ask_size: int = 0


@dataclass(frozen=True)
class SignalIntent:
    product: Product
    fair_value: FairValueEstimate
    mode: ExecutionMode = "idle"
    buy_below: float | None = None
    sell_above: float | None = None
    quote: QuoteIntent | None = None
    rationale: str = ""
    metadata: Mapping[str, Scalar] = field(default_factory=_empty_scalar_map)


# ---------------------------------------------------------------- scanner


@dataclass(frozen=True)
class ScannerConfig:
    """Controls whether and how verbosely the flow scanner runs.

    Verbosity levels:
    - 0 (default): silent — scanner runs and persists state but adds
      nothing to the decision logger. Suitable for live submission.
    - 1: flags-only — appends ``scan_flags`` to the logger event.
    - 2: full report — appends the complete ``FlowReport`` dict to the
      logger event. Intended for offline review scripts only.
    """

    enabled: bool = True
    extrema_window: int = 20
    extrema_tolerance: float = 1.0
    flow_decay: float = 0.8
    repeated_size_threshold: int = 3
    verbosity: int = 0


@dataclass(frozen=True)
class ResidualConfig:
    """Controls the optional residual capacity utilizer.

    Ships disabled (framework-only). Enable only after the enablement
    gate is passed: compare baseline vs baseline+residual on PnL, trade
    count, maker/taker mix, markouts, and time-near-limits. Record
    results in a review note before flipping the flag.
    """

    enabled: bool = False
    residual_edge: float = 2.0
    residual_size: int = 2


@dataclass(frozen=True)
class FlowReport:
    """Observational summary of trade-flow patterns for a single step.

    All fields are ephemeral — only ``flow_score`` (via
    ``ProductMemory.values``) and ``step_count`` (via
    ``ProductMemory.counters``) are persisted across calls.

    ``net_flow`` is a heuristic proxy for directional pressure, not
    true aggressor-side inference. The sign convention is: buyer-only
    trade -> +qty, seller-only -> -qty, both or neither -> 0.
    """

    product: Product
    timestamp: Timestamp
    repeated_sizes: Mapping[int, int]
    net_flow: int
    flow_score: float
    near_high: bool
    near_low: bool
    flags: tuple[str, ...]
    metadata: Mapping[str, Scalar] = field(default_factory=_empty_scalar_map)

# ========================================================================
# src/core/market_data.py
# ========================================================================

"""Raw ``TradingState`` -> canonical ``NormalizedSnapshot`` adapter.

Everything downstream of this module consumes ``NormalizedSnapshot``s, so
this is the only place that has to know how Prosperity lays out raw
order-book and trade data.

Conventions enforced here:

- Bids are sorted price-descending; asks are sorted price-ascending.
  Strategies can then rely on ``bids[0]`` being the best bid.
- Ask volumes are always returned as *positive* integers, regardless of
  whether the raw ``sell_orders`` dict uses Prosperity's negative-volume
  convention or an already-positive mirror. Zero-volume levels are
  dropped.
- Trade lists combine own and market trades and are sorted by timestamp,
  with a ``source`` tag preserved so diagnostics can distinguish them.

This module produces no orders and holds no state.
"""




class MarketDataAdapter:
    def normalize_state(self, state: TradingState) -> dict[str, NormalizedSnapshot]:
        snapshots: dict[str, NormalizedSnapshot] = {}
        for product, order_depth in state.order_depths.items():
            bids, asks = self._normalize_depth(order_depth)
            trades = self._normalize_trades(
                state.own_trades.get(product, []) if state.own_trades else [],
                state.market_trades.get(product, []) if state.market_trades else [],
            )
            snapshots[product] = NormalizedSnapshot(
                product=product,
                timestamp=state.timestamp,
                bids=bids,
                asks=asks,
                position=state.position.get(product, 0) if state.position else 0,
                trades=trades,
            )
        return snapshots

    @staticmethod
    def _normalize_depth(
        order_depth: OrderDepth,
    ) -> tuple[tuple[BookLevel, ...], tuple[BookLevel, ...]]:
        buys = getattr(order_depth, "buy_orders", {}) or {}
        sells = getattr(order_depth, "sell_orders", {}) or {}

        bids = tuple(
            BookLevel(price=int(price), volume=int(volume))
            for price, volume in sorted(buys.items(), key=lambda item: item[0], reverse=True)
            if int(volume) > 0
        )
        # Prosperity convention: sell_orders use negative volume.
        # We accept either convention and always return positive volumes.
        asks = tuple(
            BookLevel(price=int(price), volume=abs(int(volume)))
            for price, volume in sorted(sells.items(), key=lambda item: item[0])
            if int(volume) != 0
        )
        return bids, asks

    @staticmethod
    def _normalize_trades(
        own_trades: list[Trade], market_trades: list[Trade]
    ) -> tuple[TradePrint, ...]:
        combined: list[TradePrint] = []
        combined.extend(
            TradePrint(
                price=int(trade.price),
                quantity=int(trade.quantity),
                buyer=trade.buyer,
                seller=trade.seller,
                timestamp=int(trade.timestamp),
                source="own",
            )
            for trade in own_trades or []
        )
        combined.extend(
            TradePrint(
                price=int(trade.price),
                quantity=int(trade.quantity),
                buyer=trade.buyer,
                seller=trade.seller,
                timestamp=int(trade.timestamp),
                source="market",
            )
            for trade in market_trades or []
        )
        combined.sort(key=lambda trade: trade.timestamp)
        return tuple(combined)

# ========================================================================
# src/core/r3_products.py
# ========================================================================

"""R3 product constants, position limits, and time-to-expiry helper.

These are the only product-specific constants that belong in the live
submission bundle. Everything else (EDA notes, calibration results,
replay utilities) lives outside the live path.
"""


# ----------------------------------------------------------------- symbols

HYDROGEL_PACK: str = "HYDROGEL_PACK"
VELVETFRUIT_EXTRACT: str = "VELVETFRUIT_EXTRACT"

VOUCHER_STRIKES: tuple[int, ...] = (
    4000, 4500, 5000, 5100, 5200, 5300, 5400, 5500, 6000, 6500,
)

VOUCHER_PRODUCTS: tuple[str, ...] = tuple(
    f"VELVET_VOUCHER_{k}" for k in VOUCHER_STRIKES
)

# R3 data/position reference names (as they appear in the CSV and
# Prosperity TradingState). Vouchers are named VEV_<strike>.
VEV_PRODUCTS: tuple[str, ...] = tuple(f"VEV_{k}" for k in VOUCHER_STRIKES)

# Convenience map: strike → product symbol
STRIKE_TO_PRODUCT: dict[int, str] = {k: f"VEV_{k}" for k in VOUCHER_STRIKES}
PRODUCT_TO_STRIKE: dict[str, int] = {v: k for k, v in STRIKE_TO_PRODUCT.items()}

# ---------------------------------------------------------------- limits

POS_LIMITS: dict[str, int] = {
    HYDROGEL_PACK: 200,
    VELVETFRUIT_EXTRACT: 200,
    **{f"VEV_{k}": 300 for k in VOUCHER_STRIKES},
}

ALL_R3_PRODUCTS: frozenset[str] = frozenset(POS_LIMITS)

# ---------------------------------------------------------------- TTE

# TTE at R3 *final simulation* start = 5 days.
# Timestamps run 0 → 999_900 in steps of 100.
# Each 1_000_000 ticks = 1 calendar day of simulation.
TTE_DAYS_AT_R3_START: float = 5.0
TICKS_PER_DAY: int = 1_000_000


def tte_live(timestamp: int) -> float:
    """Time to expiry in days at ``timestamp`` within R3.

    The live sim starts with TTE = 5.0 at ts = 0. Each 1_000_000
    ticks consume 1 day. Returns a positive value throughout the round;
    clipped to 1e-6 to avoid BSM singularity at expiry.
    """
    remaining = TTE_DAYS_AT_R3_START - timestamp / TICKS_PER_DAY
    return max(remaining, 1e-6)

# ========================================================================
# src/options/bsm.py
# ========================================================================

"""Black-Scholes-Merton option pricing (fixes D7 for options).

Pure Python implementation with inline Abramowitz-Stegun (1964) approximation
for the standard normal CDF — scipy is NOT available in the Prosperity
submission container.

Only call options are implemented (Prosperity vouchers are calls in P3;
extend to puts when/if needed).

All functions are pure. No state, no I/O.

Reference: `engine_options.md` §2 for design decisions. The A&S 7.1.26
approximation is accurate to ~7.5e-8 — more than enough for voucher
pricing where the tick-grid rounds to 1 anyway.
"""




# ============================================================= norm CDF


# Abramowitz & Stegun 7.1.26 coefficients.
_A1 = 0.254829592
_A2 = -0.284496736
_A3 = 1.421413741
_A4 = -1.453152027
_A5 = 1.061405429
_P = 0.3275911


def norm_cdf(x: float) -> float:
    """Standard normal CDF, Abramowitz-Stegun 7.1.26 approximation.

    Accurate to ~7.5e-8. Symmetric: uses identity Φ(-x) = 1 - Φ(x).
    """
    sign = 1 if x >= 0 else -1
    abs_x = abs(x) / math.sqrt(2.0)
    t = 1.0 / (1.0 + _P * abs_x)
    y = 1.0 - (((((_A5 * t + _A4) * t) + _A3) * t + _A2) * t + _A1) * t * math.exp(
        -abs_x * abs_x
    )
    return 0.5 * (1.0 + sign * y)


def norm_pdf(x: float) -> float:
    """Standard normal PDF."""
    return math.exp(-0.5 * x * x) / math.sqrt(2.0 * math.pi)


# ============================================================= BSM call


@dataclass(frozen=True)
class BSMInputs:
    """Inputs to the Black-Scholes-Merton formula.

    Time-to-expiry is in YEARS (or whatever unit matches the vol
    annualization). Prosperity vouchers: if expiry is in 'ticks' and
    vol is per-tick, T stays in ticks. If vol is daily, T in days. The
    caller must be consistent.
    """

    spot: float
    """Underlying price S."""

    strike: float
    """Strike price K."""

    time_to_expiry: float
    """T — time until expiration, in units matching volatility."""

    volatility: float
    """σ — standard deviation per unit time (same unit as T)."""

    risk_free_rate: float = 0.0
    """r — assumed 0 in Prosperity (no cash leg accrues interest)."""

    def __post_init__(self) -> None:
        if self.spot <= 0:
            raise ValueError("spot must be > 0")
        if self.strike <= 0:
            raise ValueError("strike must be > 0")
        if self.time_to_expiry <= 0:
            raise ValueError("time_to_expiry must be > 0")
        if self.volatility <= 0:
            raise ValueError("volatility must be > 0")


def _d1_d2(inputs: BSMInputs) -> tuple[float, float]:
    sigma_sqrt_t = inputs.volatility * math.sqrt(inputs.time_to_expiry)
    d1 = (
        math.log(inputs.spot / inputs.strike)
        + (inputs.risk_free_rate + 0.5 * inputs.volatility ** 2) * inputs.time_to_expiry
    ) / sigma_sqrt_t
    d2 = d1 - sigma_sqrt_t
    return d1, d2


def call_price(inputs: BSMInputs) -> float:
    """Black-Scholes call price."""
    d1, d2 = _d1_d2(inputs)
    return (
        inputs.spot * norm_cdf(d1)
        - inputs.strike
        * math.exp(-inputs.risk_free_rate * inputs.time_to_expiry)
        * norm_cdf(d2)
    )


# ============================================================= Greeks


@dataclass(frozen=True)
class Greeks:
    """Option Greeks for a call."""

    delta: float  # ∂C/∂S
    gamma: float  # ∂²C/∂S²
    vega: float   # ∂C/∂σ (per 1.00 absolute change in vol, not per %)
    theta: float  # ∂C/∂T (per unit of T)


def call_greeks(inputs: BSMInputs) -> Greeks:
    """Compute delta/gamma/vega/theta for a call.

    Theta is returned per UNIT of time-to-expiry (negative, since
    extrinsic value decays). If T is in days, theta is per-day.
    """
    d1, d2 = _d1_d2(inputs)
    sqrt_t = math.sqrt(inputs.time_to_expiry)
    pdf_d1 = norm_pdf(d1)

    delta = norm_cdf(d1)
    gamma = pdf_d1 / (inputs.spot * inputs.volatility * sqrt_t)
    vega = inputs.spot * pdf_d1 * sqrt_t
    theta = (
        -inputs.spot * pdf_d1 * inputs.volatility / (2.0 * sqrt_t)
        - inputs.risk_free_rate
        * inputs.strike
        * math.exp(-inputs.risk_free_rate * inputs.time_to_expiry)
        * norm_cdf(d2)
    )
    return Greeks(delta=delta, gamma=gamma, vega=vega, theta=theta)


# ============================================================= IV solver


def implied_vol(
    market_price: float,
    *,
    spot: float,
    strike: float,
    time_to_expiry: float,
    risk_free_rate: float = 0.0,
    lo: float = 0.001,
    hi: float = 5.0,
    tol: float = 1e-6,
    max_iter: int = 60,
) -> float | None:
    """Bisection-based IV solver.

    Returns None if no IV in [lo, hi] produces a call price matching
    market_price (e.g., market_price below intrinsic or above cap).
    """
    if market_price <= 0:
        return None
    intrinsic = max(0.0, spot - strike * math.exp(-risk_free_rate * time_to_expiry))
    if market_price < intrinsic - tol:
        return None  # arbitrage or misquote
    if spot <= 0 or strike <= 0 or time_to_expiry <= 0:
        return None

    def f(sigma: float) -> float:
        inputs = BSMInputs(
            spot=spot, strike=strike, time_to_expiry=time_to_expiry,
            volatility=sigma, risk_free_rate=risk_free_rate,
        )
        return call_price(inputs) - market_price

    f_lo = f(lo)
    f_hi = f(hi)

    # Exact-bracket endpoints: if f(lo) or f(hi) is already within tolerance,
    # return that value directly. CRITICAL fix: `f_lo * f_mid < 0` becomes
    # vacuously false when f_lo == 0, causing the solver to converge on `hi`
    # for deep-ITM options where call_price(sigma=lo) already matches market.
    if abs(f_lo) < tol:
        return lo
    if abs(f_hi) < tol:
        return hi

    # Monotonic in sigma; need sign change to bracket root.
    if f_lo * f_hi > 0:
        # Root is outside [lo, hi]. Try widening hi up to 10 once.
        if f_hi < 0 and hi < 10.0:
            wider = 10.0
            f_wider = f(wider)
            if f_wider > 0:
                hi = wider
                f_hi = f_wider
            else:
                return None
        else:
            return None

    for _ in range(max_iter):
        mid = 0.5 * (lo + hi)
        f_mid = f(mid)
        if abs(f_mid) < tol:
            return mid
        if f_lo * f_mid < 0:
            hi = mid
            f_hi = f_mid
        else:
            lo = mid
            f_lo = f_mid
    return 0.5 * (lo + hi)

# ========================================================================
# src/strategies/round_3/velvet_options_rolling_iv.py
# ========================================================================

"""Rolling-IV residual taker sleeve for R3 VELVET vouchers.

Research status: diagnostic candidate, not a proven production sleeve.

The model deliberately avoids the static cross-sectional smile as the
primary fair value. On the historical tapes, per-strike rolling IV residuals
were more robust than a global smile fit, and this implementation mirrors
that simpler hypothesis:

    fair[K, t] = Black-Scholes(S_t, K, T_t, EWMA_IV[K, t-1])

It only trades core strikes where the option surface actually moves. Deep ITM
and lottery vouchers are excluded until separate evidence justifies them.
"""





@dataclass(frozen=True)
class RollingIVOptionsConfig:
    traded_strikes: tuple[int, ...] = (5000, 5100, 5200, 5300, 5400, 5500)
    entry_edge: float = 0.5
    exit_edge: float = 0.10
    residual_scale: float = 4.0
    max_position: int = 120
    max_order: int = 18
    max_abs_delta: float = 80.0
    rolling_halflife: float = 40.0
    rolling_warmup: int = 40
    terminal_flatten_start: int | None = None
    iv_min: float = 0.001
    iv_max: float = 0.20


@dataclass
class RollingIVOptionsState:
    ewma_iv: dict[str, float] = field(default_factory=dict)
    counts: dict[str, int] = field(default_factory=dict)

    def to_state(self) -> dict:
        return {
            "ewma_iv": dict(self.ewma_iv),
            "counts": dict(self.counts),
        }

    def from_state(self, blob: dict) -> None:
        if not isinstance(blob, dict):
            return
        ewma = blob.get("ewma_iv", {})
        counts = blob.get("counts", {})
        if isinstance(ewma, dict):
            self.ewma_iv = {
                str(product): float(value)
                for product, value in ewma.items()
                if _is_finite_number(value)
            }
        if isinstance(counts, dict):
            parsed: dict[str, int] = {}
            for product, value in counts.items():
                try:
                    parsed[str(product)] = int(value)
                except (TypeError, ValueError):
                    continue
            self.counts = parsed


DEFAULT_ROLLING_IV_OPTIONS_CONFIG = RollingIVOptionsConfig()


def rolling_iv_option_orders(
    *,
    velvet_snapshot: NormalizedSnapshot | None,
    option_snapshots: dict[str, NormalizedSnapshot],
    positions: dict[str, int],
    timestamp: int,
    state: RollingIVOptionsState,
    config: RollingIVOptionsConfig = DEFAULT_ROLLING_IV_OPTIONS_CONFIG,
) -> list[Order]:
    """Generate L1 taker orders from rolling-IV residuals.

    State update is part of this function: each tick trades against the
    previous EWMA IV and only then observes the current market IV.
    """
    if velvet_snapshot is None or velvet_snapshot.mid is None:
        return []

    spot = float(velvet_snapshot.mid)
    tte_days = tte_live(timestamp)
    if spot <= 0 or tte_days <= 0:
        return []

    working_positions = dict(positions)
    orders: list[Order] = []

    views = _build_option_views(
        spot=spot,
        tte_days=tte_days,
        option_snapshots=option_snapshots,
        state=state,
        config=config,
    )

    if (
        config.terminal_flatten_start is not None
        and timestamp >= config.terminal_flatten_start
    ):
        orders.extend(
            _flatten_orders(
                option_snapshots=option_snapshots,
                working_positions=working_positions,
                views=views,
                config=config,
            )
        )
        _observe_current_ivs(
            spot=spot,
            tte_days=tte_days,
            option_snapshots=option_snapshots,
            state=state,
            config=config,
        )
        return orders

    for strike in config.traded_strikes:
        product = STRIKE_TO_PRODUCT[strike]
        snapshot = option_snapshots.get(product)
        view = views.get(product)
        if snapshot is None or view is None:
            continue
        bid = snapshot.best_bid
        ask = snapshot.best_ask
        mid = snapshot.mid
        if bid is None or ask is None or mid is None:
            continue

        fair = view.fair
        signal = fair - float(mid)
        if abs(signal) <= config.exit_edge:
            target = 0
        else:
            raw_target = int(round(signal / config.residual_scale * config.max_position))
            target = max(-config.max_position, min(config.max_position, raw_target))

        current = working_positions.get(product, 0)
        desired_delta = target - current
        if desired_delta > 0:
            edge = fair - ask.price
            if edge >= config.entry_edge:
                qty = min(desired_delta, config.max_order, ask.volume)
                qty = _clip_for_position(product, qty, working_positions, config, side=1)
                qty = _clip_for_delta_cap(
                    product=product,
                    qty=qty,
                    side=1,
                    positions=working_positions,
                    views=views,
                    config=config,
                )
                if qty > 0:
                    orders.append(Order(product, ask.price, qty))
                    working_positions[product] = current + qty
        elif desired_delta < 0:
            edge = bid.price - fair
            if edge >= config.entry_edge:
                qty = min(-desired_delta, config.max_order, bid.volume)
                qty = _clip_for_position(product, qty, working_positions, config, side=-1)
                qty = _clip_for_delta_cap(
                    product=product,
                    qty=qty,
                    side=-1,
                    positions=working_positions,
                    views=views,
                    config=config,
                )
                if qty > 0:
                    orders.append(Order(product, bid.price, -qty))
                    working_positions[product] = current - qty

    _observe_current_ivs(
        spot=spot,
        tte_days=tte_days,
        option_snapshots=option_snapshots,
        state=state,
        config=config,
    )
    return orders


@dataclass(frozen=True)
class _OptionView:
    fair: float
    delta: float


def _build_option_views(
    *,
    spot: float,
    tte_days: float,
    option_snapshots: dict[str, NormalizedSnapshot],
    state: RollingIVOptionsState,
    config: RollingIVOptionsConfig,
) -> dict[str, _OptionView]:
    views: dict[str, _OptionView] = {}
    for strike in config.traded_strikes:
        product = STRIKE_TO_PRODUCT[strike]
        if state.counts.get(product, 0) < config.rolling_warmup:
            continue
        vol = state.ewma_iv.get(product)
        if vol is None or not (config.iv_min <= vol <= config.iv_max):
            continue
        snapshot = option_snapshots.get(product)
        if snapshot is None or snapshot.mid is None:
            continue
        maybe_view = _price_and_delta(spot, float(strike), tte_days, vol)
        if maybe_view is not None:
            views[product] = maybe_view
    return views


def _observe_current_ivs(
    *,
    spot: float,
    tte_days: float,
    option_snapshots: dict[str, NormalizedSnapshot],
    state: RollingIVOptionsState,
    config: RollingIVOptionsConfig,
) -> None:
    alpha = 1.0 - 0.5 ** (1.0 / config.rolling_halflife)
    for strike in config.traded_strikes:
        product = STRIKE_TO_PRODUCT[strike]
        snapshot = option_snapshots.get(product)
        if snapshot is None or snapshot.mid is None:
            continue
        iv = implied_vol(
            float(snapshot.mid),
            spot=spot,
            strike=float(strike),
            time_to_expiry=tte_days,
            lo=config.iv_min,
            hi=1.0,
        )
        if iv is None or not (config.iv_min <= iv <= config.iv_max):
            continue
        previous = state.ewma_iv.get(product)
        state.ewma_iv[product] = (
            iv if previous is None else alpha * iv + (1.0 - alpha) * previous
        )
        state.counts[product] = state.counts.get(product, 0) + 1


def _price_and_delta(
    spot: float,
    strike: float,
    tte_days: float,
    vol: float,
) -> _OptionView | None:
    try:
        inputs = BSMInputs(
            spot=spot,
            strike=strike,
            time_to_expiry=tte_days,
            volatility=vol,
        )
        fair = call_price(inputs)
        delta = call_greeks(inputs).delta
    except (ValueError, OverflowError, ZeroDivisionError):
        return None
    if not (math.isfinite(fair) and math.isfinite(delta)):
        return None
    return _OptionView(fair=fair, delta=max(0.0, min(1.0, delta)))


def _flatten_orders(
    *,
    option_snapshots: dict[str, NormalizedSnapshot],
    working_positions: dict[str, int],
    views: dict[str, _OptionView],
    config: RollingIVOptionsConfig,
) -> list[Order]:
    orders: list[Order] = []
    for strike in config.traded_strikes:
        product = STRIKE_TO_PRODUCT[strike]
        pos = working_positions.get(product, 0)
        if pos == 0:
            continue
        snapshot = option_snapshots.get(product)
        if snapshot is None:
            continue
        if pos > 0:
            bid = snapshot.best_bid
            if bid is None:
                continue
            qty = min(pos, config.max_order, bid.volume)
            qty = _clip_for_delta_cap(
                product=product,
                qty=qty,
                side=-1,
                positions=working_positions,
                views=views,
                config=config,
            )
            if qty > 0:
                orders.append(Order(product, bid.price, -qty))
                working_positions[product] = pos - qty
        else:
            ask = snapshot.best_ask
            if ask is None:
                continue
            qty = min(-pos, config.max_order, ask.volume)
            qty = _clip_for_delta_cap(
                product=product,
                qty=qty,
                side=1,
                positions=working_positions,
                views=views,
                config=config,
            )
            if qty > 0:
                orders.append(Order(product, ask.price, qty))
                working_positions[product] = pos + qty
    return orders


def _clip_for_position(
    product: str,
    qty: int,
    positions: dict[str, int],
    config: RollingIVOptionsConfig,
    *,
    side: int,
) -> int:
    if qty <= 0:
        return 0
    exchange_limit = POS_LIMITS.get(product, 300)
    limit = min(exchange_limit, config.max_position)
    current = positions.get(product, 0)
    if side > 0:
        return max(0, min(qty, limit - current))
    return max(0, min(qty, limit + current))


def _clip_for_delta_cap(
    *,
    product: str,
    qty: int,
    side: int,
    positions: dict[str, int],
    views: dict[str, _OptionView],
    config: RollingIVOptionsConfig,
) -> int:
    if qty <= 0:
        return 0
    current_delta = _net_delta(positions, views)
    delta_per_unit = views.get(product, _OptionView(0.0, 0.5)).delta
    for clipped in range(qty, 0, -1):
        projected = current_delta + side * clipped * delta_per_unit
        if (
            abs(projected) <= config.max_abs_delta
            or abs(projected) < abs(current_delta)
        ):
            return clipped
    return 0


def _net_delta(
    positions: dict[str, int],
    views: dict[str, _OptionView],
) -> float:
    total = 0.0
    for product, view in views.items():
        total += positions.get(product, 0) * view.delta
    return total


def _is_finite_number(value: object) -> bool:
    try:
        return math.isfinite(float(value))
    except (TypeError, ValueError):
        return False

# ========================================================================
# src/engines/r3_velvet_options_engine.py
# ========================================================================

"""Minimal live engine for the isolated R3 VELVET/options branch."""




class R3VelvetOptionsEngine:
    """VELVET/options-only engine for attribution uploads."""

    def __init__(self) -> None:
        self._state = RollingIVOptionsState()
        self._config = RollingIVOptionsConfig(terminal_flatten_start=None)

    def to_state(self) -> dict:
        return {"rolling_iv_options": self._state.to_state()}

    def from_state(self, blob: dict) -> None:
        if not isinstance(blob, dict):
            return
        rolling_blob = blob.get("rolling_iv_options", {})
        if isinstance(rolling_blob, dict):
            self._state.from_state(rolling_blob)

    def step(
        self,
        *,
        snapshots: dict[str, NormalizedSnapshot],
        positions: dict[str, int],
        timestamp: int,
    ) -> list[Order]:
        option_snaps: dict[str, NormalizedSnapshot] = {}
        for strike in VOUCHER_STRIKES:
            product = f"VEV_{strike}"
            snap = snapshots.get(product)
            if snap is not None:
                option_snaps[product] = snap

        return rolling_iv_option_orders(
            velvet_snapshot=snapshots.get(VELVETFRUIT_EXTRACT),
            option_snapshots=option_snaps,
            positions=positions,
            timestamp=timestamp,
            state=self._state,
            config=self._config,
        )

# ========================================================================
# src/engines/r3_velvet_options_factory.py
# ========================================================================

"""Slim R3 VELVET/options submission factory.

This profile intentionally bypasses the generic Trader/orchestrator stack so
the diagnostic upload stays below the Prosperity bundle-size limit.
"""





class Trader:
    """Zero-arg Prosperity Trader for the isolated VELVET/options sleeve."""

    def __init__(self) -> None:
        self.market_data = MarketDataAdapter()
        self.engine = R3VelvetOptionsEngine()

    def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
        try:
            blob = _load_state_blob(state.traderData)
            engine_blob = blob.get("engine", {})
            if isinstance(engine_blob, dict):
                self.engine.from_state(engine_blob)

            snapshots = self.market_data.normalize_state(state)
            positions = {product: snap.position for product, snap in snapshots.items()}
            orders = self.engine.step(
                snapshots=snapshots,
                positions=positions,
                timestamp=int(state.timestamp),
            )

            grouped: dict[str, list[Order]] = defaultdict(list)
            for order in orders:
                grouped[order.symbol].append(order)

            next_blob = {"v": 1, "engine": self.engine.to_state()}
            trader_data = json.dumps(next_blob, separators=(",", ":"))
            return dict(grouped), 0, trader_data
        except Exception:
            return {}, 0, state.traderData


def _load_state_blob(raw: str | None) -> dict:
    if not raw:
        return {}
    try:
        blob = json.loads(raw)
    except (TypeError, ValueError):
        return {}
    return blob if isinstance(blob, dict) else {}
